### ISSUE TITLE
运行train.py和test.py出现下面问题

### ISSUE THREAD

**Issue by enhuishu** [mdswyz/DMD#16]
OSError: Can't load tokenizer for 'bert-base-uncased'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'bert-base-uncased' is the correct path to a directory containing all relevant files for a BertTokenizer tokenizer.

**Comment by Issac304** [comment]
how to solve it？
