### ISSUE TITLE
Supplementary file

### ISSUE THREAD

**Issue by ShiQingHongYa** [mdswyz/DMD#3]
It is a nice work of emotion recognition, could you please provide the supplementary file including more experimental details? Thank you very much!

**Comment by mdswyz** [comment]
Link of supplementary file: https://drive.google.com/file/d/1sWGGDYPMrDqZA4p7bvLBsiL7yvt2iLzL/view?usp=sharing

**Comment by ShiQingHongYa** [comment]
Thanks for your work. Besides changing the parameter "use_bert" in config.json, could you please provide other parameters when training the model without Bert on aligned and unaligned settings? Under the same seed, the results of the aligned setting with Bert are almost consistent with the paper, but the results of other settings without Bert are worse.
