### ISSUE TITLE
About MOSI dataset

### ISSUE THREAD

**Issue by mishimario** [mdswyz/DMD#9]
Hi I have a question about MOSI dataset.
I think that the vision feature's final dimension is 20 and the audio final dimension is 5 according to your config.
But On your paper , it's 35, 74 respectively.
And I checked the official github repo of MOSI dataset. I couldn't find the way of downloading those 20 and 5 dimensional features. Did you do something on that dataset like using a subset or extracting some mean features.
Or you used an earlier version of that dataset?
Thank you in advance!

**Comment by mdswyz** [comment]
Thanks for your concern. I just checked the dataset's official website (https://github.com/CMU-MultiComp-Lab/CMU-MultimodalSDK) and noticed that the download links had been removed. But what is certain is that this is the original feature setting for the MOSI dataset. This can also be derived from the metadata of the dataset, but I can't make the metadata available to you because the author has blocked it due to privacy concerns. 35, 74 generally refer to MOSEI's setting.

**Comment by mishimario** [comment]
Thank you for replying ! 
The metadata that you mean is kind of Youtube video?

Hmm okey then it can't be helped. Maybe I can use your dataset that you share :)

And can I ask about MOSEI too?
According to your paper, the total number of MOSEI is 22856.
But one of original paper is 23453. And other papers' one are different.
What is this difference? Do you know something?

**Comment by mdswyz** [comment]
The original number of video clips was 23453 (from the dataset paper), but the final number of extracted features was 22856. I guess is that some low-quality samples were removed. Some papers reported 23453, and some papers reported 22856. We reported on actual numbers in our papers. This field is always weird.

**Comment by mishimario** [comment]
I see. Maybe I guess some data that don't have some modality is removed.(kind of missing modality)

**Comment by mishimario** [comment]
Sorry Can I ask about that metadata of MOSI?
You just downloaded it and used it? Or you encoded it to 5, 20 dimensional features using some way?

**Comment by luilui23333** [comment]
> Sorry Can I ask about that metadata of MOSI? You just downloaded it and used it? Or you encoded it to 5, 20 dimensional features using some way?

Sorry to bother you.Have you figured it out? I have the same confusion.
I searched for the official MOSI and MOSEI （links below）.
https://drive.google.com/drive/folders/1uEK737LXB9jAlf9kyqRs6B9N6cDncodq
https://drive.google.com/drive/folders/1A_hTmifi824gypelGobgl2M-5Rw9VWHv
It seems like that DMD author @mdswyz  did some data preprocessing on the official MOSI and MOSEI raw data or the official preprocessed data (.pkl files and .hdf5 files)?
I am not sure :)
